=== anis-ben-said/semantic-models-analysis/sldt-semantic-models/io.catenax.just_in_sequence_part/3.0.0/gen/JustInSequencePart-schema.json
{
  "$schema" : "http://json-schema.org/draft-04/schema",
  "description" : "A just-in-sequence part is an instantiation of a (design-)part, where the particular instantiation can be uniquely identified by means of a combination of several IDs related to a just-in-sequence process.",
  "type" : "object",
  "components" : {
    "schemas" : {
      "urn_samm_io.catenax.shared.uuid_2.0.0_UuidV4Trait" : {
        "type" : "string",
        "description" : "The provided regular expression ensures that the UUID is composed of five groups of characters separated by hyphens, in the form 8-4-4-4-12 for a total of 36 characters (32 hexadecimal characters and 4 hyphens), optionally prefixed by \"urn:uuid:\" to make it an IRI.",
        "pattern" : "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
      },
      "urn_samm_io.catenax.just_in_sequence_part_3.0.0_KeyTrait" : {
        "type" : "string",
        "description" : "Constraint that ensures that the predefined keys are used.",
        "pattern" : "^(manufacturerId|jisNumber|jisCallDate|parentOrderNumber|customKey:\\w+)$"
      },
      "urn_samm_io.catenax.just_in_sequence_part_3.0.0_ValueCharacteristic" : {
        "type" : "string",
        "description" : "The value of an identifier."
      },
      "urn_samm_io.catenax.just_in_sequence_part_3.0.0_KeyValueList" : {
        "description" : "A list of key value pairs for local identifiers, which are composed of a key and a corresponding value.",
        "type" : "object",
        "properties" : {
          "key" : {
            "description" : "The key of a local identifier. ",
            "$ref" : "#/components/schemas/urn_samm_io.catenax.just_in_sequence_part_3.0.0_KeyTrait"
          },
          "value" : {
            "description" : "The value of an identifier.",
            "$ref" : "#/components/schemas/urn_samm_io.catenax.just_in_sequence_part_3.0.0_ValueCharacteristic"
          }
        },
        "required" : [ "key", "value" ]
      },
      "urn_samm_io.catenax.just_in_sequence_part_3.0.0_LocalIdentifierCharacteristic" : {
        "description" : "A single just-in-sequence part may have multiple attributes, that uniquely identify a that part in a specific dataspace (e.g. the manufacturer`s dataspace)",
        "type" : "array",
        "items" : {
          "$ref" : "#/components/schemas/urn_samm_io.catenax.just_in_sequence_part_3.0.0_KeyValueList"
        },
        "uniqueItems" : true
      },
      "urn_samm_io.catenax.just_in_sequence_part_3.0.0_DateTimeTrait" : {
        "type" : "string",
        "description" : "Regular Expression to enable UTC and Timezone formats and the possibility to exclude time information.",
        "pattern" : "^(?:[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(?:[.][0-9]+)?Z|[0-9]{4}-[0-9]{2}-[0-9]{2}(?:T[0-9]{2}:[0-9]{2}:[0-9]{2}(?:[.][0-9]+)?(?:Z|[+-][0-9]{2}:[0-9]{2}))?)$"
      },
      "urn_samm_io.catenax.just_in_sequence_part_3.0.0_ProductionCountryCodeTrait" : {
        "type" : "string",
        "description" : "Regular Expression that ensures a three-letter code ",
        "pattern" : "^[A-Z][A-Z][A-Z]$"
      },
      "urn_samm_io.catenax.shared.business_partner_number_2.0.0_BpnsTrait" : {
        "type" : "string",
        "description" : "The provided regular expression ensures that the BPNS is composed of prefix 'BPNS', 10 digits and two alphanumeric letters.",
        "pattern" : "^BPNS[a-zA-Z0-9]{12}$"
      },
      "urn_samm_io.catenax.shared.part_site_information_as_built_2.0.0_FunctionCharacteristic" : {
        "type" : "string",
        "description" : "Describes the characteristics of the function for a site related to the respective part.",
        "enum" : [ "production", "warehouse", "spare part warehouse" ]
      },
      "urn_samm_io.catenax.shared.part_site_information_as_built_2.0.0_SitesEntity" : {
        "description" : "Describes the ID and function of a site for the associated part in the AsBuilt context(e.g. SerialPart, Batch, jIS).",
        "type" : "object",
        "properties" : {
          "catenaXsiteId" : {
            "description" : "The identifier of the site according to Catena-X BPDM. The catenaXsiteId must be a valid Catena-X BPN. The BPN is a unique, unchangeable identifier for Business Partners / company locations from foundation to closure, regardless of the different business relationships / structures between or within the Business Partners or company locations.",
            "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.business_partner_number_2.0.0_BpnsTrait"
          },
          "function" : {
            "description" : "The function of the site in relation to the part(i.e. the activity within the value chain of the part that is performed at the site)",
            "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.part_site_information_as_built_2.0.0_FunctionCharacteristic"
          }
        },
        "required" : [ "catenaXsiteId", "function" ]
      },
      "urn_samm_io.catenax.shared.part_site_information_as_built_2.0.0_SitesCharacteristic" : {
        "description" : "Sites Characteristic",
        "type" : "array",
        "items" : {
          "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.part_site_information_as_built_2.0.0_SitesEntity"
        },
        "uniqueItems" : true
      },
      "urn_samm_io.catenax.just_in_sequence_part_3.0.0_ManufacturingCharacteristic" : {
        "description" : "Characteristic to describe manufacturing related data",
        "type" : "object",
        "properties" : {
          "date" : {
            "description" : "Timestamp of the manufacturing date as the final step in production process (e.g. final quality check, ready-for-shipment event)",
            "$ref" : "#/components/schemas/urn_samm_io.catenax.just_in_sequence_part_3.0.0_DateTimeTrait"
          },
          "country" : {
            "description" : "Country code where the part was manufactured",
            "$ref" : "#/components/schemas/urn_samm_io.catenax.just_in_sequence_part_3.0.0_ProductionCountryCodeTrait"
          },
          "sites" : {
            "description" : "A site is a delimited geographical area where a legal entity does business(geographical address with geo coordinates).A site always has a primary physical address. It is possible that further physical addresses are specified for the site. P.O. box details are only possible in addition to the physical address. A site has a 1:n relation to addresses, means at least 1 address is necessary and multiple addresses are possible.",
            "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.part_site_information_as_built_2.0.0_SitesCharacteristic"
          }
        },
        "required" : [ "date" ]
      },
      "urn_samm_io.catenax.just_in_sequence_part_3.0.0_PartIdCharacteristic" : {
        "type" : "string",
        "description" : "The part ID is a multi-character string, usually assigned by an ERP system. Alternatively the ID of the part family can be used if no specific part ID exists."
      },
      "urn_samm_io.catenax.just_in_sequence_part_3.0.0_PartNameCharacteristic" : {
        "type" : "string",
        "description" : "Part Name in string format from the respective system in the value chain"
      },
      "urn_samm_io.catenax.shared.part_classification_1.0.0_ClassificationStandardCharacteristic" : {
        "type" : "string",
        "description" : "Identified classification standards that align to the Catena-X needs."
      },
      "urn_samm_io.catenax.shared.part_classification_1.0.0_ClassificationIDCharacteristic" : {
        "type" : "string",
        "description" : "It can be numeric or a string, depending on the chosen classification standard."
      },
      "urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text" : {
        "type" : "string",
        "description" : "Describes a Property which contains plain text. This is intended exclusively for human readable strings, not for identifiers, measurement values, etc."
      },
      "urn_samm_io.catenax.shared.part_classification_1.0.0_ClassificationEntity" : {
        "description" : "Encapsulates data related to the classification of the part.",
        "type" : "object",
        "properties" : {
          "classificationStandard" : {
            "description" : "Identified classification standards that align to the Catena-X needs.",
            "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.part_classification_1.0.0_ClassificationStandardCharacteristic"
          },
          "classificationID" : {
            "description" : "The classification ID of the part type according to the corresponding standard definition mentioned in the key value pair.",
            "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.part_classification_1.0.0_ClassificationIDCharacteristic"
          },
          "classificationDescription" : {
            "description" : "Optional property describing the classification standard.",
            "$ref" : "#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_Text"
          }
        },
        "required" : [ "classificationStandard", "classificationID" ]
      },
      "urn_samm_io.catenax.shared.part_classification_1.0.0_ClassificationCharacteristic" : {
        "description" : "Classification characteristic enabling a set of further properties.",
        "type" : "array",
        "items" : {
          "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.part_classification_1.0.0_ClassificationEntity"
        },
        "uniqueItems" : true
      },
      "urn_samm_io.catenax.just_in_sequence_part_3.0.0_PartTypeInformationCharacteristic" : {
        "description" : "The characteristics of the part type",
        "type" : "object",
        "properties" : {
          "manufacturerPartId" : {
            "description" : "Part ID as assigned by the manufacturer of the part. The manufacturer Part ID identifies the part (as designed)in the manufacturer`s dataspace. The Part ID does not reference a specific instance of a part and thus should not be confused with the serial number or any other instance IDs. \nIf no specific part ID exists a part family ID may be substituted for it.",
            "$ref" : "#/components/schemas/urn_samm_io.catenax.just_in_sequence_part_3.0.0_PartIdCharacteristic"
          },
          "customerPartId" : {
            "description" : "Part ID as assigned by the customer of the part. The customer Part ID identifies the part (as designed)in the customer`s dataspace. The Part ID does not reference a specific instance of a part and thus should not be confused with the serial number or any other instance IDs. \nIf no specific part ID exists a part family ID may be substituted for it.\n",
            "$ref" : "#/components/schemas/urn_samm_io.catenax.just_in_sequence_part_3.0.0_PartIdCharacteristic"
          },
          "nameAtManufacturer" : {
            "description" : "Name of the part as assigned by the manufacturer",
            "$ref" : "#/components/schemas/urn_samm_io.catenax.just_in_sequence_part_3.0.0_PartNameCharacteristic"
          },
          "nameAtCustomer" : {
            "description" : "Name of the part as assigned by the customer",
            "$ref" : "#/components/schemas/urn_samm_io.catenax.just_in_sequence_part_3.0.0_PartNameCharacteristic"
          },
          "partClassification" : {
            "description" : "Property describing the classification of a part.",
            "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.part_classification_1.0.0_ClassificationCharacteristic"
          }
        },
        "required" : [ "nameAtManufacturer" ]
      }
    }
  },
  "properties" : {
    "catenaXId" : {
      "description" : "The fully anonymous Catena-X ID of the just-in-sequence part, valid for the Catena-X dataspace.",
      "$ref" : "#/components/schemas/urn_samm_io.catenax.shared.uuid_2.0.0_UuidV4Trait"
    },
    "localIdentifiers" : {
      "description" : "A local identifier enables identification of a part in a specific dataspace, but is not unique in Catena-X dataspace. Multiple local identifiers may exist.",
      "$ref" : "#/components/schemas/urn_samm_io.catenax.just_in_sequence_part_3.0.0_LocalIdentifierCharacteristic"
    },
    "manufacturingInformation" : {
      "description" : "Information from manufacturing process, such as manufacturing date and manufacturing country",
      "$ref" : "#/components/schemas/urn_samm_io.catenax.just_in_sequence_part_3.0.0_ManufacturingCharacteristic"
    },
    "partTypeInformation" : {
      "description" : "The part type or part family from which the just-in-sequence part has been instantiated.",
      "$ref" : "#/components/schemas/urn_samm_io.catenax.just_in_sequence_part_3.0.0_PartTypeInformationCharacteristic"
    }
  },
  "required" : [ "catenaXId", "localIdentifiers", "manufacturingInformation", "partTypeInformation" ]
}

=== anis-ben-said/semantic-models-analysis/sldt-semantic-models/io.catenax.just_in_sequence_part/3.0.0/gen/JustInSequencePart.json
{
  "localIdentifiers" : [ {
    "value" : "12345678ABC",
    "key" : "jisNumber"
  } ],
  "manufacturingInformation" : {
    "date" : "2022-02-04T14:48:54",
    "country" : "HUR",
    "sites" : [ {
      "catenaXsiteId" : "BPNS1234567890ZZ",
      "function" : "production"
    } ]
  },
  "catenaXId" : "urn:uuid:580d3adf-1981-44a0-a214-13d6ceed9379",
  "partTypeInformation" : {
    "partClassification" : [ {
      "classificationStandard" : "IEC",
      "classificationID" : "61360- 2:2012 ",
      "classificationDescription" : "Standard data element types with associated classification scheme for electric components."
    } ],
    "manufacturerPartId" : "123-0.740-3434-A",
    "customerPartId" : "PRT-12345",
    "nameAtManufacturer" : "Mirror left",
    "nameAtCustomer" : "side element A"
  }
}
